### ISSUE TITLE
Meaning of command-line switches?

### ISSUE THREAD

**Issue by goloroden** [hpcloud/npm-lazy-mirror#17]
When configuring npm-lazy-mirror via CLI switches, the documentation tells you to call it like this:

```
npm-lazy-mirror -p <port> -a <remote_address> -b <bind_address> --cache_dir /npm-data
```

Now, what do the various arguments mean? `-p` and `--cache_dir` are pretty obvious, I think but what do `-a` and `-b` mean, and what are they good for? Are they mandatory? And either way, what addresses do I have to provide here?

It would be nice if the documentation could explain this with a little more detail.

**Comment by jdpaton** [comment]
You can use the `-h` option to view a short description of each flag, but yes we need docs.

`-a` - Is the external DNS/IP of the server that npm clients should be able to reach. This is injected into each NPM package in the mirror so the client knows where to get dependencies etc.

`-b` - Is the bind address, which local interface address the mirror server should listen on. Default is 0.0.0.0 (all).

**Comment by goloroden** [comment]
Great, thanks a lot for the explanation :-)
