### ISSUE TITLE
Publishing modules not supported by design?

### ISSUE THREAD

**Issue by goloroden** [hpcloud/npm-lazy-mirror#18]
In the very end, the documentation tells you under _Caveats_:

> You cannot use this mirror for publishing modules or user management, such requests will be forwarded to the upstream registry for processing.

Is this a decision _by design_, or is it _by accident_? In other words: Shall the current behavior stay this way (which I actually hope for), or do you plan to change it?

**Comment by jdpaton** [comment]
It was by design as transparently supporting private modules through this registry requires more thought about client interoperability. 

I think if it were to be ever implemented, it would be an optional feature.

**Comment by goloroden** [comment]
Awesome, thanks :-))
