### ISSUE TITLE
Impossible to disable http server

### ISSUE THREAD

**Issue by LucsT** [hpcloud/npm-lazy-mirror#3]
I'm in trouble to desactivate http server 

$ npm-lazy-mirror --http_enable false
[Mon Dec 16 2013 15:37:06 GMT+0000 (UTC)] INFO Lazy mirror (HTTP) is listening @ 127.0.0.1:2000 External host: localhost
[Mon Dec 16 2013 15:37:06 GMT+0000 (UTC)] INFO Lazy mirror (HTTPS) is listening @ 127.0.0.1:2001 External host: localhost

The code seems to overwrite arguments or config file.  (argv || config || true)

Trying few solutions 

Looking

**Comment by LucsT** [comment]
I found a workaround.

The config.http_enabled variable is '  || true ' so is always true.

Please see this commit, https://github.com/LucsT/npm-lazy-mirror/commit/7e604fbe560a89fea8bde4f3304fb61d231c7cfd

Don't want to push 2 pull request side by side, so i can push that, if the first is validate (https debug)

Lucas

**Comment by jdpaton** [comment]
Thanks, PR merged in 119a6cce0a.  Though I think that HTTP and HTTPS should be allowed in the same server process, so I updated this PR in 1f897c129266e2.

This means you can run:
-  `--http_enabled` and only get HTTP
- `--https_enabled` and only get HTTPS
-  `--http_enabled --https_enabled` to get both.
- Supply neither to get HTTP only by default.

HTH.
