### ISSUE TITLE
Use Https to connect registry.npmjs.org

### ISSUE THREAD

**Issue by LucsT** [hpcloud/npm-lazy-mirror#4]
Hello.

A issue is the connection between nodejs and npm-lazy-mirror.
An attacker could intercept and rcorrupt a packet before delivering in the cache

@Jdpaton it's an issue for me, What's you opinion?
More generally, what's you futur expectation for this soft?

Should we keep an http acces?

For secure it, we must : 
    Use https instead http,  Some code modification here because http was hard coded.
    Verify the certificate selfsigned use : Probably by providing it manually.

Maybe I'll try to fix it in next 2 weeks, if anyone want before, do it, and thank's.

Lucas

**Comment by jdpaton** [comment]
This is a good feature request. I've implemented it in 4385ca1ef2c34e6bf51681856479613a9a968058.

That commit provides two additional configuration options:
- `--upstream_use_https` - Use HTTPS when contacting the upstream registry
- `--upstream_verify_ssl` - Ignore SSL cerificate validation errors with the upstream registry.

You can also store these options `upstream_use_https` & `upstream_verify_ssl` and others in a JSON configuration file with the `-C` option.

Note that `npm` also does sha256 sums on each .tgz package loaded into the registry which is stored in the package manifest, which makes it just _slightly_ more difficult to corrupt from a MITM attack.

HTH.
