### ISSUE TITLE
Add support for remote proxy usage

### ISSUE THREAD

**Issue by tuxmea** [hpcloud/npm-lazy-mirror#5]
I planned to use npm-lazy-mirror in an internal network where all systems have to use a proxy for outbound connections.
The npm-lazy-mirror  does not honor npm proxy settings (npm config) or http_proxy/https_proxy environment variables.

Either use the defaults (from npm or env variables) or allow a configuration section for proxy configuration.

**Comment by jdpaton** [comment]
To elaborate on this the search order for proxy settings is now:
1. CLI option flags `--http_proxy`, `--https_proxy`
2. Reading from `npm config proxy/https-proxy`
3. Environment variables HTTP{S}_PROXY

Tested with mitmproxy.

HTH.

**Comment by jandubois** [comment]
Why use only HTTP_PROXY but not http_proxy evnironment variables? I find that most apps either only support the lowercase variant (git, curl), or both, but only supporting uppercase seems rare.
