### ISSUE TITLE
npm-lazy-mirror fails on fetching packages with multiple version in package name

### ISSUE THREAD

**Issue by tuxmea** [hpcloud/npm-lazy-mirror#7]
[Thu Jan 30 2014 10:12:13 GMT+0100 (CET)] INFO GET /dateformat/-/dateformat-1.0.7-1.2.3.tgz
[Thu Jan 30 2014 10:12:20 GMT+0100 (CET)] INFO Resource not found: /dateformat/-/dateformat-1.0.7-1.2.3.tgz
[Thu Jan 30 2014 10:13:24 GMT+0100 (CET)] INFO GET /dateformat

**Comment by jdpaton** [comment]
Thanks for reporting this issue.

**Comment by fxa** [comment]
I would like to reopen this bug.
With this fix now it works for the LATEST version 
    npm install --registry http://my.lazy.mirror dateformat
but still it does not work with a dedicated version:
    npm install --registry http://my.lazy.mirror dateformat@1.0.2-1.2.3
(karma-coverage uses an old version of dateformat)
