### ISSUE TITLE
Cannot install wordwrap

### ISSUE THREAD

**Issue by fxa** [hpcloud/npm-lazy-mirror#9]
I think the problem is, that wordwrap has no release on github.
(Btw. is a strange module. Absolute small and 40.000 downloads per day)

npm ERR! Error: failed to fetch from registry: wordwrap
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm-registry-client/lib/get.js:134:18)
npm ERR!     at cb (/usr/lib/node_modules/npm-registry-client/lib/request.js:27:9)
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm-registry-client/lib/request.js:122:16)
npm ERR!     at cb (/usr/lib/node_modules/npm-registry-client/lib/request.js:158:9)
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm-registry-client/lib/request.js:303:12)
npm ERR!     at Request.self.callback (/usr/lib/node_modules/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/node_modules/request/index.js:891:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/node_modules/request/index.js:842:12)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

**Comment by jdpaton** [comment]
Was it a particular wordwrap version? It seems to install without issue on the latest npm-lazy-mirror (0.2.3).

**Comment by jdpaton** [comment]
Please re-open if this is still an issue on the latest > 0.3.x

**Comment by fxa** [comment]
Sorry, I forgot to close.

I have no problem with 0.3

Thank you!

Von: Jamie [mailto:notifications@github.com] 
Gesendet: Freitag, 28. März 2014 23:15
An: ActiveState/npm-lazy-mirror
Cc: Franz X Antesberger
Betreff: Re: [npm-lazy-mirror] Cannot install wordwrap (#9)

Closed #9 https://github.com/ActiveState/npm-lazy-mirror/issues/9 .
